language: nix

sudo: required

matrix:
  include:
    - addons: {apt: {packages: [curl,git]}}

install:
 - git clone https://github.com/reflex-frp/reflex-platform
 - echo "" | ./reflex-platform/scripts/setup
 - ./reflex-platform/scripts/work-on ghcjs ./. --run "echo Prepared environment"

script:
 - ./reflex-platform/scripts/work-on ghcjs ./. --run "cabal new-build --ghcjs all"

